# Generated by Django 4.0.6 on 2022-07-24 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_blacklistedtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='token_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
